/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pj_test_util_DESTool */

#ifndef _Included_com_pj_test_util_DESTool
#define _Included_com_pj_test_util_DESTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pj_test_util_DESTool
 * Method:    md5Encrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pj_test_util_DESTool_md5Encrypt
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_pj_test_util_DESTool
 * Method:    encrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pj_test_util_DESTool_encrypt
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_pj_test_util_DESTool
 * Method:    decrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pj_test_util_DESTool_decrypt
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
