//
// Created by Administrator on 2016/2/26.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sse_android_listedcompany_OptionToolJni */

#ifndef _Included_com_pj_test_util_DESTool
#define _Included_com_pj_test_util_DESTool
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_pj_test_util_DESTool
 * Method:    l
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pj_test_util_DESTool_decrypt
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_pj_test_util_DESTool
 * Method:    a
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pj_test_util_DESTool_encrypt
        (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif